begin;

alter table public._siraman_config_tamu_dari
  add column if not exists whatsapp_session_id text,
  add column if not exists whatsapp_enabled boolean not null default false,
  add column if not exists whatsapp_phone text,
  add column if not exists whatsapp_connected_at timestamptz;

alter table public._siraman_invitation_bulk_batches
  add column if not exists provider text not null default 'legacy',
  add column if not exists external_batch_id text,
  add column if not exists session_id text;

update public._siraman_invitation_bulk_batches
set external_batch_id = openwa_batch_id
where external_batch_id is null;

update public._siraman_invitation_bulk_batches
set provider = 'legacy'
where provider = 'openwa';

alter table public._siraman_invitation_bulk_batches
  alter column provider set default 'legacy',
  alter column external_batch_id set not null,
  alter column openwa_batch_id drop not null;

create unique index if not exists _siraman_bulk_batches_external_id_idx
  on public._siraman_invitation_bulk_batches(external_batch_id);

create table if not exists public._siraman_whatsapp_sessions (
  id text primary key,
  tamu_from text not null unique,
  status text not null default 'disconnected'
    check (status in ('disconnected', 'connecting', 'qr', 'connected', 'reconnecting', 'logged_out', 'error')),
  phone_number text,
  display_name text,
  last_error text,
  connected_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public._siraman_whatsapp_auth (
  session_id text not null references public._siraman_whatsapp_sessions(id) on delete cascade,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (session_id, key)
);

create table if not exists public._siraman_whatsapp_logs (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public._siraman_invitation_bulk_batches(id) on delete cascade,
  level text not null default 'info' check (level in ('info', 'success', 'warning', 'error')),
  event text not null,
  message text not null,
  guest_id bigint references public._siraman_data_tamu(id) on delete set null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists _siraman_whatsapp_sessions_status_idx
  on public._siraman_whatsapp_sessions(status);
create index if not exists _siraman_whatsapp_logs_batch_created_idx
  on public._siraman_whatsapp_logs(batch_id, created_at);
create index if not exists _siraman_bulk_batches_provider_idx
  on public._siraman_invitation_bulk_batches(provider, created_at desc);

alter table public._siraman_whatsapp_sessions enable row level security;
alter table public._siraman_whatsapp_auth enable row level security;
alter table public._siraman_whatsapp_logs enable row level security;

grant select, insert, update, delete on public._siraman_whatsapp_sessions to authenticated, service_role;
grant select, insert, update, delete on public._siraman_whatsapp_auth to authenticated, service_role;
grant select, insert, update, delete on public._siraman_whatsapp_logs to authenticated, service_role;
grant usage, select on sequence public._siraman_whatsapp_logs_id_seq to authenticated, service_role;

drop policy if exists "_siraman_Wedding admin full access" on public._siraman_whatsapp_sessions;
create policy "_siraman_Wedding admin full access"
  on public._siraman_whatsapp_sessions
  for all
  to authenticated
  using (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com')
  with check (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com');

drop policy if exists "_siraman_Wedding admin full access" on public._siraman_whatsapp_auth;
create policy "_siraman_Wedding admin full access"
  on public._siraman_whatsapp_auth
  for all
  to authenticated
  using (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com')
  with check (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com');

drop policy if exists "_siraman_Wedding admin full access" on public._siraman_whatsapp_logs;
create policy "_siraman_Wedding admin full access"
  on public._siraman_whatsapp_logs
  for all
  to authenticated
  using (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com')
  with check (lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'maulanamalikjb147@gmail.com');

commit;
